# Generated by Django 6.0.3 on 2026-03-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('event', 'Event'), ('play', 'Play'), ('sport', 'Sport'), ('activity', 'Activity')], default='movie', max_length=20),
        ),
    ]
