# Generated by Django 6.0.3 on 2026-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='2h', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Drama', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
