# Generated by Django 6.0.3 on 2026-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_duration_movie_genre_movie_language_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('theater', 'seat_number'), name='unique_seat_per_theater'),
        ),
    ]
